# This file is part of project link.developers/ld-node-facedetector-2.
# It is copyrighted by the contributors recorded in the version control history of the file,
# available from its original location https://gitlab.com/link.developers.beta/ld-node-facedetector-2.
#
# SPDX-License-Identifier: MPL-2.0

package:
  name: "ld-node-facedetector-2"
  version: {{ BUILD_VERSION }}

source:
  git_url: ../

build:
  skip: 
    true # [aarch64]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ld-cmake-tools
    - flatc

  host:
    - link2-cpp
    - opencv
    - dlib
    - ld-lib-image
    - cuda=9.0
    - cudnn

  run:
    - link2
    - opencv
    - dlib
    - ld-lib-image
    - cuda=9.0
    - cudnn

test:
  commands:
    - "ld-node-facedetector-2 --help"

extra:
  git-commit: {{ GIT_FULL_HASH }}

about:
  home: "https://gitlab.com/link.developers.beta/ld-node-facedetector-2"
  license: "MPL-2.0"
  license_file: "LICENSE"
  summary: "A link2 node to detect faces in an image."
